### ISSUE TITLE
Data download link is invalid

### ISSUE THREAD

**Issue by PamelaDDD** [Anastasiais-ml/TCE-CVSE#1]
Hello author, can you provide other ways to download data? The data download link you provided is invalid

**Comment by MingliangLiang3** [comment]
Sorry, the dataset created by SCAN, I don't think I'm allowed to share data in any other way. You can ask the authors of  SCAN.

**Comment by MingliangLiang3** [comment]
> Hello author, can you provide other ways to download data? The data download link you provided is invalid

Please refer [vse++](https://github.com/fartashf/vsepp.git)
